eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        service-url:
            defaultZone: http://localhost:8761/eureka
    instance:
        prefer-ip-address: true
server:
    port: 8084
spring:
    application:
        name: API-GATEWAY
    cloud:
        gateway:
            routes:
                - id: EPDMS-REACTIVE-APP
                  uri: lb://EPDMS-REACTIVE-APP
                  predicates:
                      - Path=/message/**, /api/employee/**
    main:
        allow-circular-references: true
    r2dbc:
        password: postgres
        url: r2dbc:postgresql://localhost:5432/epdms
        username: postgres
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'
